version: "3.8"

# Lista de containers
services: 
  app:
    build: .
    command: npm start
    ports: 
      - "5000:5000"
    volumes: 
      - .:/src
  #   depends_on: 
  #     - mysql_server
  
  # mysql_server:
  #   image: mysql:8.0
  #   environment: 
  #     - MYSQL_DATABASE=test_db
  #     - MYSQL_USER=dan
  #     - MYSQL_PASSWORD=secret
  #     - MYSQL_ROOT_PASSWORD=secret